version: "3.8"
services:
  server:
    # privileged: true
    build: ./server
    ports:
      - "5000:5000"
    links:
      - streamlit-app
      - mongo
      # - vue-app

    restart: always
  # vue-app:
  #   build: ./vue-app
  #   ports:
  #     - "5000:5000"
  streamlit-app:
    build: ./streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ".:/usr/src/app/"
    command: "streamlit run main.py"

  mongo:
    image: mongo
    restart: always
    # volumes:
    #   - "~/mongo/data:/data/db" #persistent database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
